name: generate changelog and create pre release

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2
      #   with:
      #     fetch-depth: 0
      # - name: Automatic GitHub Release
      #   uses: justincy/github-action-npm-release@2.0.1
      #   id: release
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Generate changelog step
      - name: Generate Changelog
        uses: mikepenz/release-changelog-builder-action@v1
        id: changelog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      # Create pre-release
      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: false
          prerelease: true
          body: ${{ steps.changelog.outputs.changelog }}
          token: ${{ secrets.GITHUB_TOKEN }}
